# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name}}
  labels:
    app: {{.Values.deployment.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.deployment.name}}
  template:
    metadata:
      labels:
        app: {{.Values.deployment.name}}
    spec:
      containers:
      - name: {{.Values.deployment.name}}
        image: {{.Values.image.repository}}:{{.Values.image.tag}} 
        ports:
        - containerPort: {{.Values.container.port}} 
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
