# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherforecast-api
  labels:
    app: weatherforecast-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherforecast-api
  template:
    metadata:
      labels:
        app: weatherforecast-api
    spec:
      containers:
      - name: weatherforecast-api
        image: docker.io/daleospina/weatherforecast-api:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: weatherforecast-api
spec:
  selector:
    app: weatherforecast-api
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer